name: platform_channel
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_riverpod: ^2.6.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  permission_handler: ^12.0.1
  file_picker: ^10.2.0
  path_provider: ^2.1.5
  image: ^4.5.4
  flutter_sliding_toast: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  pigeon: ^25.3.0
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
